/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'book-page',
    path: '/book-page',
    component: 'layout.base',
    meta: {
      title: 'book-page',
      i18nKey: 'route.book-page',
      icon: 'mdi:monitor-dashboard',
      order: 2,
      roles: ['R_SUPER', 'R_ADMIN']
    },
    children: [
      {
        name: 'book-page_article',
        path: '/book-page/article/:id',
        component: 'view.book-page_article',
        meta: {
          title: 'book-page_article',
          hideInMenu: true,
          i18nKey: 'route.book-page_article'
        }
      },
      {
        name: 'book-page_book',
        path: '/book-page/book',
        component: 'view.book-page_book',
        meta: {
          title: 'book-page_book',
          i18nKey: 'route.book-page_book'
        }
      },
      {
        name: 'book-page_lesson',
        path: '/book-page/lesson/:id',
        component: 'view.book-page_lesson',
        meta: {
          title: 'book-page_lesson',
          hideInMenu: true,
          i18nKey: 'route.book-page_lesson'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
